---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: predictiveautoscalers.scaler.cs.usc.edu
spec:
  group: scaler.cs.usc.edu
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetDeployment:
                  type: string
                targetHPA:
                  type: string
                maxReplicas:
                  type: integer
                  minimum: 1
                historyRetentionDays:
                  type: integer
                  minimum: 1
                  default: 7
                updateInterval:
                  type: integer
                  minimum: 1
                  default: 5
                predictionWindowMinutes:
                  type: integer
                  minimum: 1
                  default: 4
                predictionWindowSeconds:
                  type: integer
                  minimum: 1
                  default: 240
                  description: "Number of seconds to look ahead for predictions"
                historicalWeight:
                  type: number
                  minimum: 0
                  maximum: 1
                  default: 0.7
                currentWeight:
                  type: number
                  minimum: 0
                  maximum: 1
                  default: 0.3
              required:
                - targetDeployment
                - targetHPA
                - maxReplicas
            status:
              type: object
              properties:
                lastUpdated:
                  type: string
                currentPrediction:
                  type: integer
                lastError:
                  type: string
                create_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                update_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                delete_fn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: predictiveautoscalers
    singular: predictiveautoscaler
    kind: PredictiveAutoscaler
    shortNames:
      - pa
---
