apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: 10.10.1.1:5000/simpleweb:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "400m"
          limits:
            cpu: "420m"
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - "date +%s > /tmp/start_time"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              if [ $(($(date +%s) - $(cat /tmp/start_time))) -gt 240 ]; then exit 0; else exit 1; fi
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 100
          successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb
spec:
  selector:
    app: simpleweb
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 80
  type: ClusterIP