apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleweb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleweb
  template:
    metadata:
      labels:
        app: simpleweb
    spec:
      containers:
      - name: simpleweb
        image: simpleweb:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: simpleweb
spec:
  selector:
    app: simpleweb
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 80
  type: ClusterIP
