apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictive-autoscaler-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictive-autoscaler-controller
  template:
    metadata:
      labels:
        app: predictive-autoscaler-controller
    spec:
      serviceAccountName: predictive-autoscaler-sa
      containers:
      - name: controller
        image: anirudhr120100/csci555-predictive-autoscaler:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: historical-data
          mountPath: /data
      volumes:
      - name: historical-data
        persistentVolumeClaim:
          claimName: historical-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: historical-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 