---
apiVersion: scaler.cs.usc.edu/v1
kind: PredictiveAutoscaler
metadata:
  name: simpleweb-predictor
spec:
  targetDeployment: simpleweb-deployment
  targetHPA: simpleweb-hpa
  maxReplicas: 10
  historyRetentionDays: 7
  updateInterval: 5  # minutes
  # predictionWindowMinutes: 10  # Deprecated
  predictionWindowSeconds: 15  # Using seconds for finer-grained predictions
  historicalWeight: 0.7
  currentWeight: 0.3
---
