---
apiVersion: scaler.cs.usc.edu/v1
kind: PredictiveAutoscaler
metadata:
  name: simpleweb-predictor
spec:
  targetDeployment: simpleweb-deployment
  targetHPA: simpleweb-hpa
  maxReplicas: 10
  historyRetentionDays: 7
  updateInterval: 1  # Reduced to 1 minute for testing with 1-minute interval data
  predictionWindowMinutes: 15  # Deprecated
  predictionWindowSeconds: 900  # Using 60 seconds (1 minute) for traffic_1_interval.json
  historicalWeight: 0.7
  currentWeight: 0.3
---
