apiVersion: v1
kind: ServiceAccount
metadata:
  name: predictive-autoscaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: predictive-autoscaler-role
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["scaler.cs.columbia.edu"]
  resources: ["predictiveautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["scaler.cs.columbia.edu"]
  resources: ["predictiveautoscalers/status"]
  verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: predictive-autoscaler-role-binding
subjects:
- kind: ServiceAccount
  name: predictive-autoscaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: predictive-autoscaler-role
  apiGroup: rbac.authorization.k8s.io 